version: '3'
services:
  db:     # service DB
    image: mongo:latest
  backend: # service backend
    image: node:latest
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && node app"
  frontend: # service frontend
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 80:80
