version: '3'
volumes:
  data:
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html/
      # reverse proxy configuration
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    # networks:
    #   - web
    # depends_on:
    #   - app